---
- name: Export required variables in environment
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/environment"
    line: "export DOMAIN={{ domain }}"
    regexp: "^export DOMAIN={{ domain }}$"
    state: present

- name: Export required variables in environment
  ansible.builtin.lineinfile:
    dest: "~{{ ansible_user }}/.bashrc"
    line: "export DOMAIN={{ domain }}"
    regexp: "^export DOMAIN={{ domain }}$"
    state: present

- name: Install rsync
  become: true
  ansible.builtin.apt:
    name: rsync
    state: present

- name: Synchronize service configuration files with rsync
  become: true
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/home_server/srv"
    dest: /
  notify:
    - "restart home_server services"

- name: Create Traefik password
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    digest="$( printf "%s:%s:%s" "{{ traefik_user }}" traefik "{{ traefik_password }}" | md5sum | awk '{print $1}' )"
    printf "%s:%s:%s\n" "{{ traefik_user }}" traefik "$digest" > /srv/traefik/.htdigest
  args:
    creates:
      /srv/traefik/.htdigest
  notify:
    - "restart home_server services"

- name: Make sure the containers managed by docker compose are started.
  community.docker.docker_compose:
    project_name: home_server
    project_src: /srv
    state: present
    remove_orphans: true
  environment:
    DOMAIN: "{{ domain }}"
    OWNCLOUD_USER: "{{ owncloud_user }}"
    OWNCLOUD_PASSWORD: "{{ owncloud_password }}"
