http:
  middlewares:
    crowdsec-bouncer:
      forwardauth:
        address: http://crowdsec_bouncer:8080/api/v1/forwardAuth
        trustForwardHeader: true
    ratelimiter:
      rateLimit:
        average: 30
        burst: 25
