raspberry_pi:
  hosts:
    raspi:
      ansible_host: broker.corentinpape.com
      ansible_port: 1882
  vars:
    ansible_user: pi
    dyndns_server: "dynv6.com"
    dyndns_domain: "cocopapsbroker.dynv6.net"
    dyndns_token: "{{ lookup('ansible.builtin.env', 'DYNDNS_BROKER_TOKEN', default='') }}"
home_server:
  hosts:
    home:
      ansible_host: homeserver.corentinpape.com
      ansible_port: 22
  vars:
    ansible_user: coco
    ansible_host_key_checking: no
    wol_interface: enp4s0
    dyndns_server: "dynv6.com"
    dyndns_domain: "cocopapshomeserver.dynv6.net"
    dyndns_token: "{{ lookup('ansible.builtin.env', 'DYNDNS_HOMESERVER_TOKEN', default='') }}"
