---
- name: Restart the Docker service
  become: true
  ansible.builtin.systemd:
    name: docker.service
    daemon_reload: yes
    state: restarted
    enabled: true
    masked: no
  listen: "restart docker service"
