- name: Update Raspberry Pi (Waker)
  hosts: all
  collections:
    - devsec.hardening
    - ansible.posix
    - community.general
  roles:
    - { role: copy_ssh_key, tags: copy_ssh_key }
    - { role: ssh_hardening, tags: ssh_hardening }
    - { role: core, tags: core }
    - { role: dyndns, tags: dyndns }
    - { role: firewall, tags: firewall }
    - { role: mosquitto, tags: mosquitto }
    - { role: waker, tags: waker }
    - { role: docker, tags: docker }
  tasks:
    - name: Allow all access to Mosquitto MQTT server port 1883
      become: true
      community.general.ufw:
        rule: allow
        port: 1883
  vars:
    ssh_pam_support: false
    ssh_use_pam: false
    ssh_kerberos_support: false
    ssh_server_password_login: false
    sshd_authenticationmethods: publickey
    ssh_permit_root_login: without-password
