global:
  sendAnonymousUsage: false

log:
  level: "INFO"
  format: "common"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    swarmMode: false

api:
  dashboard: true
  debug: false
  insecure: false

entryPoints:
  insecure:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "secure"
          scheme: "https"
          permanent: true
  secure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "saulunaire@gmail.com"
      storage: "/srv/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: "EC256"
      httpChallenge:
        entryPoint: "insecure"
