global:
  sendAnonymousUsage: false

log:
  level: "DEBUG"
  format: json

providers:
  kubernetesIngress: {}

api:
  dashboard: false
  debug: false
  insecure: false

entryPoints:
  insecure:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "secure"
          scheme: "https"
          permanent: true
  secure:
    address: ":443"

ping:
  entryPoint: "insecure"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "corentin0pape@gmail.com"
      storage: "/srv/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: "EC256"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

http:
  middlewares:
    ratelimiter:
      rateLimit:
        average: 30
        burst: 25
