endpoints:
  - name: blog
    url: "https://blog.corentinpape.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: grafana
    url: "https://grafana.corentinpape.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: homepage
    url: "https://home.corentinpape.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: jenkins
    url: "https://jenkins.corentinpape.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: cloud
    url: "https://cloud.corentinpape.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms
