- name: Update Raspberry Pi (Waker)
  hosts: all
  collections:
    - devsec.hardening
    - ansible.posix
  roles:
    - { role: copy_ssh_key, tags: copy_ssh_key }
    - { role: ssh_hardening, tags: ssh_hardening }
    - { role: core, tags: core }
    - { role: dyndns, tags: dyndns }
    - { role: mosquitto, tags: mosquitto }
    - { role: waker, tags: waker }
  vars:
    ssh_pam_support: false
    ssh_use_pam: false
    ssh_kerberos_support: false
    ssh_server_password_login: false
    sshd_authenticationmethods: publickey
    ssh_permit_root_login: without-password
