---
- name: Restart the containers managed by docker compose.
  community.docker.docker_compose:
    project_name: home_server
    project_src: /srv
    state: present
    restarted: true
  environment:
    DOMAIN: "{{ domain }}"
    OWNCLOUD_USER: "{{ owncloud_user }}"
    OWNCLOUD_PASSWORD: "{{ owncloud_password }}"
  listen: "restart home_server services"
