name: Build the code

on:
  push:

jobs:
  ansible-check-syntax:
    name: ansible-check-syntax
    runs-on: ubuntu-latest
    container: cocopaps/ansible-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Ansible playbook syntax
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: playbook.yml
          directory: ./
          requirements: requirements.yml
          options: |
            --inventory inventory.yml
            --syntax-check
