name: Deployment pipeline
on:
  push:
    branches:
      - main
concurrency: deployment
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    container: cocopaps/ci-tools:latest
    steps:
      - uses: actions/checkout@v3
      - name: Deployment
        env:
          PASSBOLT_CI_ACS_BASE64: ${{secrets.PASSBOLT_CI_ACS_BASE64}}
          PASSBOLT_CI_PASSWORD: ${{secrets.PASSBOLT_CI_PASSWORD}}
          SSH_CI_PRIVATEKEY_BASE64: ${{secrets.SSH_CI_PRIVATEKEY_BASE64}}
        run: |
          ./ci-wrapper.sh apply -auto-approve -lock-timeout=5m
