name: Ensure that the code respect the coding-style using a linter

on:
  push:

jobs:
  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    container: cocopaps/ansible-ci:latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Ansible-Lint to check for Ansible common mistakes
        run: ansible-lint playbook.yml
