name: Check Terraform plan
on:
  pull_request:
    branches:
      - main
jobs:
  plan:
    name: plan
    runs-on: ubuntu-latest
    container: cocopaps/ci-tools:latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform plan
        env:
          PASSBOLT_CI_ACS_BASE64: ${{secrets.PASSBOLT_CI_ACS_BASE64}}
          PASSBOLT_CI_PASSWORD: ${{secrets.PASSBOLT_CI_PASSWORD}}
          SSH_CI_PRIVATEKEY_BASE64: ${{secrets.SSH_CI_PRIVATEKEY_BASE64}}
        run: |
          ./ci-wrapper.sh plan -lock-timeout=5m
