name: Setup machines
on:
  workflow_dispatch:

concurrency: deployment

jobs:
  setup:
    name: Setup machines
    runs-on: ubuntu-latest
    container: cocopaps/ci-tools:latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - name: Run setup
        env:
          PASSBOLT_CI_ACS_BASE64: ${{secrets.PASSBOLT_CI_ACS_BASE64}}
          PASSBOLT_CI_PASSWORD: ${{secrets.PASSBOLT_CI_PASSWORD}}
          SSH_CI_PRIVATEKEY_BASE64: ${{secrets.SSH_CI_PRIVATEKEY_BASE64}}
        run: |
          ./ci-wrapper.sh bash -c 'cd machines && terraform init && terraform apply -auto-approve -lock-timeout=5m'
      - name: Setup Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Setup machines run failed
            webhookUrl: ${{ secrets.CI_DISCORD_WEBHOOK }}
