storage:
  type: sqlite
  path: /srv/data.db
endpoints:
  - name: blog
    url: "https://blog.cocopaps.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: minecraft
    url: "tcp://mc.cocopaps.com:25565"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"

  - name: homepage
    url: "https://home.cocopaps.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: cloud
    url: "https://cloud.cocopaps.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: minecraft dns
    url: "8.8.8.8"
    interval: 30s
    dns:
      query-name: "mc.cocopaps.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

  - name: cloud dns
    url: "8.8.8.8"
    interval: 30s
    dns:
      query-name: "cloud.cocopaps.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

  - name: homepage dns
    url: "8.8.8.8"
    interval: 30s
    dns:
      query-name: "home.cocopaps.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

  - name: gatus dns
    url: "8.8.8.8"
    interval: 30s
    dns:
      query-name: "gatus.cocopaps.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
