endpoints:
  - name: blog
    url: "https://blog.cocopaps.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: minecraft
    url: "tcp://mc.cocopaps.com:25565"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"

  - name: youp0m
    url: "https://youp0m.cocopaps.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: homepage
    url: "https://home.cocopaps.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: cloud
    url: "https://cloud.cocopaps.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms
